# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.8.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: amber
description: Broadcast prerecordings media database 🛋️
docs: true
docsurl: https://radio-aktywne.github.io/amber
envprefix: AMBER
imagename: databases/amber
port: 10610
registry: true
releases: true
reponame: amber
repourl: https://github.com/radio-aktywne/amber
webport: 10611
